export const FUNNY_TOY_NAMES = [
  "Wobblekins",
  "Sir Squeakington",
  "Professor Fluffbottom",
  "Captain Giggles",
  "Baron Von Snuggles",
  "Pickle McWiggle",
  "Bumblesnort",
  "Twinkle Toes McGee",
  "Lord Wibblewobble",
  "Princess Sparklepants",
  "Mister Noodlearms",
  "Duchess Fuzzywump",
  "Bongo Bananapeel",
  "Ziggy Zoomzoom",
  "Waffles McFluffernutter",
  "Sprocket Dinglehopper",
  "Bubbles O'Toole",
  "Snickerdoodle Jones",
  "Razzmatazz Rumpus",
  "Doodle McSprocket",
  "Giggly Puffington",
  "Squish Mallow",
  "Bonkers McBonkface",
  "Tinker Twizzle",
  "Flibbertigibbet",
  "Mumbles McSqueaky",
  "Zippy Zoinks",
  "Pudding Pop",
  "Wigglesworth III",
  "Noodle Kaboodle",
  "Biscuit Thunderpaws",
  "Jellybean Jamboree",
  "Snugglemuffin Supreme",
  "Pippin Poppyseed",
  "Fuzzy Wuzzy Bear",
  "Tater Tot Tornado",
  "Whiskers McFloof",
  "Boogie Woogie Bot",
  "Sprinkles Stardust",
  "Chuckles McChuckleface",
  "Dizzy Doodlebug",
  "Marshmallow Mayhem",
  "Scrambles O'Brien",
  "Pogo Pumpernickel",
  "Snort McSnortface",
  "Twizzler Tornado",
  "Boopsy Daisy",
  "Rumble Tumble",
  "Squeegee McSquish",
  "Wombat Wonderpants",
  "Nifty Nibbles",
  "Gobstopper Gary",
  "Tumbles McTumbleton",
  "Zippy Zappington",
  "Scooter McBooter",
  "Fizzy Pop Rocket",
  "Bumper Stumper",
  "Wiggly Waggly Woo",
  "Chompers McGee",
  "Dazzle Razzle",
  "Flumpy Dumpling",
  "Gizmo Gadgeteer",
  "Hopscotch Harry",
  "Jumbles McJumbleton",
  "Kazoo Kazaam",
  "Loopy Lou Lou",
  "Muffin Top Murphy",
  "Nugget McNuggetson",
  "Oopsie Daisy Duke",
  "Pipsqueak Patterson",
  "Quibble Quacksworth",
  "Rumbly Tumbly Bear",
  "Squishy Squashington",
  "Tickles McTickleton",
  "Umbrella Unicorn",
  "Vroomy McVroomface",
  "Wacky Tacky Taco",
  "Xylophone Xavier",
  "Yoyo Yodeler",
  "Zonkers Zapplepop",
  "Fluffy McStuffins",
  "Bouncy Bouncerton",
  "Cuddles Von Hugs",
  "Dinky Doodad",
  "Elfie Sparklenose",
  "Frazzle Dazzle",
  "Goober Grape",
  "Hiccup Hooligan",
  "Itsy Bitsy Bot",
  "Jolly Jellyroll",
  "Kooky Kazooie",
  "Lumpy Bumpkins",
  "Muddles McPuddles",
  "Niblet Noodlehead",
  "Oinky Boinky",
  "Peppy Peppermint",
  "Quirky Quirkster",
  "Riddle Raddish",
  "Snappy Cracklepop",
  "Tubby Turbotron"
];

export function getRandomToyName(): string {
  const randomIndex = Math.floor(Math.random() * FUNNY_TOY_NAMES.length);
  return FUNNY_TOY_NAMES[randomIndex];
}
